### ISSUE TITLE
User Story #18 - Saving Summaries

### ISSUE THREAD

**Issue by irenfro** [simplif-ai/Backend#3]
## Description
As a user, I would like to save my summaries to a database.

## Tasks
- [x] Send the summary to the Database
- [x] Test the data stored in Database
- [x] Create documentation adding data to database
- [ ] Implement save button and component to view the corresponding updated list of summaries
- [x] Create endpoint to add user’s notes in the database
- [ ] Create documentation for adding user's notes in the database
- [ ] Test the added notes data in the database 
- [ ] Create endpoint for the list of user's notes in the database
- [ ] Create documentation for the list of user’s notes in the database
- [ ] Test the list of user’s notes in the database

## Acceptance Criteria
- Given that the summary is added to the Database correctly and tested properly, when implemented then it will be simple for us to access the summary data upon a user’s request.
- Given well-written documentation for sending data to the database, when we wish to send data, there will be clear and easy to read instructions on how to utilize them
- Given that the user saves a summary, the frontend will respond with correct error/success messages.
