### ISSUE TITLE
User Story #24 - Store Contact Information

### ISSUE THREAD

**Issue by irenfro** [simplif-ai/Backend#4]
## Description
As a developer, I would like to have users store their contact information.

## Tasks
- [x] Create database entry for storing additional information like phone number and email
- [x] Create backend logic and endpoint for adding contact information like phone number and email
- [x] Add documentation for backend logic and endpoint adding contact information
- [x] Test  backend logic and endpoint adding contact information
- [ ] Create input field on the frontend and implement fetch call to save

## Acceptance Criteria
- Given that we implemented the database scheme correctly, when a user logs in for the first time their information will be added to the database.
- Given that we store their contact information correctly, when we need to send an email to the user then we should be able to retrieve the user’s contact info.
- Given that we store their contact information correctly, when we need to give a user information then we should have some options in which to contact them.
