### ISSUE TITLE
User Story #23 - Slack Bot

### ISSUE THREAD

**Issue by sblatz** [simplif-ai/Backend#9]
## Description
As a user, I would like to use a Slack bot that uses simplif.ai 

## Tasks
- [x] Create Slack Bot on developer console
- [x] Give Slack Bot appropriate permissions in the console
- [x] Allow Slack Bot to call the summary API
- [x] Allow Slack Bot to listen to Slack API events so it can respond to users

## Acceptance Criteria
- Given that the Slack bot is created, when a user wishes to utilize simplif.ai’s functionality while in a slack channel, they will know how to do so.
- Given that the Slack bot is properly implemented, when a user attempts to summarize a text by calling the bot, then the Slack bot will return a summary of the text.
- Given that the Slack bot is implemented correctly, when a user wants to make a summary through slack then they should be able to easily call the bot for the summary.
